export const ROUTES = {
  home: '/',
  notFound: '/404',
  products: '/products',
  productsNew: '/products/new',
  productsBest: '/products/best',
  productsSale: '/products/sale',
  productsPerfume: '/products/perfume',
  productsShoes: '/products/shoes',
  productsBag: '/products/bag',
  productsBelt: '/products/belt',
  productsAccessory: '/products/accessory',
  productsEtc: '/products/etc',
  women: '/women',
  womenTop: '/women/top',
  womenBottom: '/women/bottom',
  womenDress: '/women/dress',
  womenOuter: '/women/outer',
  womenSkirt: '/women/skirt',
  womenSet: '/women/set',
  /** @deprecated 이전 경로 — 리다이렉트용 */
  womenTops: '/women/tops',
  womenBottoms: '/women/bottoms',
  womenDresses: '/women/dresses',
  womenShoes: '/women/shoes',
  womenMisc: '/women/misc',
  men: '/men',
  menTop: '/men/top',
  menBottom: '/men/bottom',
  menOuter: '/men/outer',
  menSet: '/men/set',
  /** @deprecated 이전 경로 — 리다이렉트용 */
  menTops: '/men/tops',
  menBottoms: '/men/bottoms',
  menShoes: '/men/shoes',
  menMisc: '/men/misc',
  live: '/live',
  cart: '/cart',
  checkout: '/checkout',
  orderComplete: '/order-complete',
  signin: '/signin',
  signup: '/signup',
  mypage: '/mypage',
  mypageOrders: '/mypage/orders',
  mypageAddresses: '/mypage/addresses',
  mypageInquiries: '/mypage/inquiries',
  mypageProfile: '/mypage/profile',
  mypageNotifications: '/mypage/notifications',
  mypageRecent: '/mypage/recent',
  /** @deprecated Use ROUTES.signin instead. */
  login: '/login',
  notices: '/notices',
  terms: '/terms',
  privacy: '/privacy',
} as const
