export const ROUTES = {
  home: '/',
  products: '/products',
  productsNew: '/products/new',
  productsBest: '/products/best',
  productsSale: '/products/sale',
  women: '/women',
  womenTops: '/women/tops',
  womenBottoms: '/women/bottoms',
  womenDresses: '/women/dresses',
  womenShoes: '/women/shoes',
  womenMisc: '/women/misc',
  men: '/men',
  menTops: '/men/tops',
  menBottoms: '/men/bottoms',
  menShoes: '/men/shoes',
  menMisc: '/men/misc',
  live: '/live',
  cart: '/cart',
  login: '/login',
  notices: '/notices',
} as const
