-- =============================================================================
-- DEPRECATED — do not run
-- =============================================================================
-- Development seed catalog removed. Products must be registered via admin only.
-- To remove legacy seed rows from an existing database, run:
--   supabase/purge-non-admin-products.sql
-- =============================================================================
